# Generated by Django 5.2.15 on 2026-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstscreen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='formula',
        ),
        migrations.AddField(
            model_name='metric',
            name='age',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='id_marine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metric',
            name='speed',
            field=models.BooleanField(default=False),
        ),
    ]
