# Generated by Django 5.2.15 on 2026-06-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstscreen', '0002_remove_metric_formula_metric_age_metric_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='intensivity',
            field=models.BooleanField(default=False, verbose_name='Интенсивность'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='age',
            field=models.BooleanField(default=False, verbose_name='Возраст данных'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='course',
            field=models.BooleanField(default=False, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='id_marine',
            field=models.BooleanField(default=False, verbose_name='ID судна'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='speed',
            field=models.BooleanField(default=False, verbose_name='Скорость'),
        ),
    ]
